from typing import final

try:
   print(number)


except:
    print("Error occured")

num1 = 39
num2 = 3
print(num1/num2)
try:
    print(num1 / num2)

except:
    print("Zero Error occured")

finally:
    print("sucess")

